#############################################################################
# Makefile for building: libi2c-ctrl.so.1.0.0
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  i2c-ctrl.pro
# Template: lib
# Command: /opt/Qt5.7/5.7/bin/qmake -spec linux-arm-gnueabi-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile i2c-ctrl.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = arm-linux-gnueabihf-gcc
CXX           = arm-linux-gnueabihf-g++
DEFINES       = -DI2CCTRL_LIBRARY -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/Qt5.7/5.7/include -I/opt/Qt5.7/5.7/mkspecs/linux-arm-gnueabi-g++
QMAKE         = /opt/Qt5.7/5.7/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = i2c-ctrl1.0.0
DISTDIR = /home/test/qt/GsMmi-solution/i2c-ctrl/.tmp/i2c-ctrl1.0.0
LINK          = arm-linux-gnueabihf-g++
LFLAGS        = -shared -Wl,-soname,libi2c-ctrl.so.1
LIBS          = $(SUBLIBS) -lpthread 
AR            = arm-linux-gnueabihf-ar cqs
RANLIB        = 
SED           = sed
STRIP         = arm-linux-gnueabihf-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = i2cctrl.cpp 
OBJECTS       = i2cctrl.o
DIST          = /opt/Qt5.7/5.7/mkspecs/features/spec_pre.prf \
		/opt/Qt5.7/5.7/mkspecs/common/unix.conf \
		/opt/Qt5.7/5.7/mkspecs/common/linux.conf \
		/opt/Qt5.7/5.7/mkspecs/common/sanitize.conf \
		/opt/Qt5.7/5.7/mkspecs/common/gcc-base.conf \
		/opt/Qt5.7/5.7/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.7/5.7/mkspecs/common/g++-base.conf \
		/opt/Qt5.7/5.7/mkspecs/common/g++-unix.conf \
		/opt/Qt5.7/5.7/mkspecs/qconfig.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_charts.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_scxml.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/Qt5.7/5.7/mkspecs/features/qt_functions.prf \
		/opt/Qt5.7/5.7/mkspecs/features/qt_config.prf \
		/opt/Qt5.7/5.7/mkspecs/linux-arm-gnueabi-g++/qmake.conf \
		/opt/Qt5.7/5.7/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/Qt5.7/5.7/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.7/5.7/mkspecs/features/toolchain.prf \
		/opt/Qt5.7/5.7/mkspecs/features/default_pre.prf \
		/opt/Qt5.7/5.7/mkspecs/features/resolve_config.prf \
		/opt/Qt5.7/5.7/mkspecs/features/default_post.prf \
		/opt/Qt5.7/5.7/mkspecs/features/qml_debug.prf \
		/opt/Qt5.7/5.7/mkspecs/features/warn_on.prf \
		/opt/Qt5.7/5.7/mkspecs/features/qt.prf \
		/opt/Qt5.7/5.7/mkspecs/features/unix/thread.prf \
		/opt/Qt5.7/5.7/mkspecs/features/file_copies.prf \
		/opt/Qt5.7/5.7/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.7/5.7/mkspecs/features/exceptions.prf \
		/opt/Qt5.7/5.7/mkspecs/features/yacc.prf \
		/opt/Qt5.7/5.7/mkspecs/features/lex.prf \
		i2c-ctrl.pro i2cctrl.h \
		i2c-ctrl_global.h i2cctrl.cpp
QMAKE_TARGET  = i2c-ctrl
DESTDIR       = 
TARGET        = libi2c-ctrl.so.1.0.0
TARGETA       = libi2c-ctrl.a
TARGET0       = libi2c-ctrl.so
TARGETD       = libi2c-ctrl.so.1.0.0
TARGET1       = libi2c-ctrl.so.1
TARGET2       = libi2c-ctrl.so.1.0


first: all
####### Build rules

$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)



staticlib: $(TARGETA)

$(TARGETA):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)

Makefile: i2c-ctrl.pro /opt/Qt5.7/5.7/mkspecs/linux-arm-gnueabi-g++/qmake.conf /opt/Qt5.7/5.7/mkspecs/features/spec_pre.prf \
		/opt/Qt5.7/5.7/mkspecs/common/unix.conf \
		/opt/Qt5.7/5.7/mkspecs/common/linux.conf \
		/opt/Qt5.7/5.7/mkspecs/common/sanitize.conf \
		/opt/Qt5.7/5.7/mkspecs/common/gcc-base.conf \
		/opt/Qt5.7/5.7/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.7/5.7/mkspecs/common/g++-base.conf \
		/opt/Qt5.7/5.7/mkspecs/common/g++-unix.conf \
		/opt/Qt5.7/5.7/mkspecs/qconfig.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_charts.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_scxml.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/Qt5.7/5.7/mkspecs/features/qt_functions.prf \
		/opt/Qt5.7/5.7/mkspecs/features/qt_config.prf \
		/opt/Qt5.7/5.7/mkspecs/linux-arm-gnueabi-g++/qmake.conf \
		/opt/Qt5.7/5.7/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/Qt5.7/5.7/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.7/5.7/mkspecs/features/toolchain.prf \
		/opt/Qt5.7/5.7/mkspecs/features/default_pre.prf \
		/opt/Qt5.7/5.7/mkspecs/features/resolve_config.prf \
		/opt/Qt5.7/5.7/mkspecs/features/default_post.prf \
		/opt/Qt5.7/5.7/mkspecs/features/qml_debug.prf \
		/opt/Qt5.7/5.7/mkspecs/features/warn_on.prf \
		/opt/Qt5.7/5.7/mkspecs/features/qt.prf \
		/opt/Qt5.7/5.7/mkspecs/features/unix/thread.prf \
		/opt/Qt5.7/5.7/mkspecs/features/file_copies.prf \
		/opt/Qt5.7/5.7/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.7/5.7/mkspecs/features/exceptions.prf \
		/opt/Qt5.7/5.7/mkspecs/features/yacc.prf \
		/opt/Qt5.7/5.7/mkspecs/features/lex.prf \
		i2c-ctrl.pro
	$(QMAKE) -spec linux-arm-gnueabi-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile i2c-ctrl.pro
/opt/Qt5.7/5.7/mkspecs/features/spec_pre.prf:
/opt/Qt5.7/5.7/mkspecs/common/unix.conf:
/opt/Qt5.7/5.7/mkspecs/common/linux.conf:
/opt/Qt5.7/5.7/mkspecs/common/sanitize.conf:
/opt/Qt5.7/5.7/mkspecs/common/gcc-base.conf:
/opt/Qt5.7/5.7/mkspecs/common/gcc-base-unix.conf:
/opt/Qt5.7/5.7/mkspecs/common/g++-base.conf:
/opt/Qt5.7/5.7/mkspecs/common/g++-unix.conf:
/opt/Qt5.7/5.7/mkspecs/qconfig.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_charts.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_charts_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_core.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_core_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_gamepad.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_gamepad_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_gui_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_help.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_help_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_network.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_network_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_nfc.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_positioning.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_purchasing.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_purchasing_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_qml_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_script.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_script_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_scripttools.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_scxml.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_sensors.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_serialbus.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_serialport.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_sql_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_svg_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_webchannel.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_websockets.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_xml_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/Qt5.7/5.7/mkspecs/modules/qt_lib_zlib_private.pri:
/opt/Qt5.7/5.7/mkspecs/features/qt_functions.prf:
/opt/Qt5.7/5.7/mkspecs/features/qt_config.prf:
/opt/Qt5.7/5.7/mkspecs/linux-arm-gnueabi-g++/qmake.conf:
/opt/Qt5.7/5.7/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/Qt5.7/5.7/mkspecs/features/exclusive_builds.prf:
/opt/Qt5.7/5.7/mkspecs/features/toolchain.prf:
/opt/Qt5.7/5.7/mkspecs/features/default_pre.prf:
/opt/Qt5.7/5.7/mkspecs/features/resolve_config.prf:
/opt/Qt5.7/5.7/mkspecs/features/default_post.prf:
/opt/Qt5.7/5.7/mkspecs/features/qml_debug.prf:
/opt/Qt5.7/5.7/mkspecs/features/warn_on.prf:
/opt/Qt5.7/5.7/mkspecs/features/qt.prf:
/opt/Qt5.7/5.7/mkspecs/features/unix/thread.prf:
/opt/Qt5.7/5.7/mkspecs/features/file_copies.prf:
/opt/Qt5.7/5.7/mkspecs/features/testcase_targets.prf:
/opt/Qt5.7/5.7/mkspecs/features/exceptions.prf:
/opt/Qt5.7/5.7/mkspecs/features/yacc.prf:
/opt/Qt5.7/5.7/mkspecs/features/lex.prf:
i2c-ctrl.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-arm-gnueabi-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile i2c-ctrl.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) $(TARGET0) $(TARGET1) $(TARGET2) $(TARGETA)
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

i2cctrl.o: i2cctrl.cpp i2cctrl.h \
		i2c-ctrl_global.h \
		/opt/Qt5.7/5.7/include/QtCore/qglobal.h \
		/opt/Qt5.7/5.7/include/QtCore/qconfig.h \
		/opt/Qt5.7/5.7/include/QtCore/qfeatures.h \
		/opt/Qt5.7/5.7/include/QtCore/qsystemdetection.h \
		/opt/Qt5.7/5.7/include/QtCore/qprocessordetection.h \
		/opt/Qt5.7/5.7/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.7/5.7/include/QtCore/qtypeinfo.h \
		/opt/Qt5.7/5.7/include/QtCore/qtypetraits.h \
		/opt/Qt5.7/5.7/include/QtCore/qisenum.h \
		/opt/Qt5.7/5.7/include/QtCore/qsysinfo.h \
		/opt/Qt5.7/5.7/include/QtCore/qlogging.h \
		/opt/Qt5.7/5.7/include/QtCore/qflags.h \
		/opt/Qt5.7/5.7/include/QtCore/qatomic.h \
		/opt/Qt5.7/5.7/include/QtCore/qbasicatomic.h \
		/opt/Qt5.7/5.7/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.7/5.7/include/QtCore/qgenericatomic.h \
		/opt/Qt5.7/5.7/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.7/5.7/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.7/5.7/include/QtCore/qglobalstatic.h \
		/opt/Qt5.7/5.7/include/QtCore/qmutex.h \
		/opt/Qt5.7/5.7/include/QtCore/qnumeric.h \
		/opt/Qt5.7/5.7/include/QtCore/qversiontagging.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o i2cctrl.o i2cctrl.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

